const issueActionTypes = {
  FETCH_ISSUES_START: " FETCH_ISSUES_START",
  FETCH_ISSUES_SUCCESS: " FETCH_ISSUES_SUCCESS",
  FETCH_ISSUES_FAILURE: " FETCH_ISSUES_FAILURE",
};

export default issueActionTypes;
